# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6100eb2f2dc20e90d4ec98da5fbdda209d178261e31456790177bcab5568545013d8440925dd48b7fabf1bac13207414e5197a2b609d9c6ee83c10f94de9448f

test:
  secret_key_base: 76aca9803b4478834774490a80c25fd9ea8f40276167a59ee30d69b0ecda473524b74316580ab28b1520d52fe942288923c8c2e1a22554ede75db708eb3419a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
